spring:
  datasource:
    url: jdbc:mysql://101.34.48.210:3306/zrgj4?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: zrgj4
    password: zrgj4
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

#showSql
logging:
  level:
    fun:
      muzi:
        campus:
          repository: debug

server:
  port: 4455
  servlet:
    context-path: /class_selection

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: countsql
